### PR TITLE
EotW Retexture

### PR DESCRIPTION
**Pull request by Aethyus**
Please pull
👉👈

-> Hatchets files need to be renamed by axes

### CODE REVIEW

**Comment by FirstMegaGame4** [comment]
pull is the action of receiving files from upstream :)

what you want now is the pr to be merged

I'll review it when it'll be done

**Comment by Aethyus** [comment]
🤓👆

**Comment by FirstMegaGame4** [comment]
will just refactor some files before merging it, probably tomorrow

**Comment by FirstMegaGame4** [comment]
I'll close this PR, since I applied patches on #5

**Pull request closed without merging**
